# Generated by Django 3.2 on 2022-01-16 00:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("archived", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("telegram", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=250)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ads.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("archived", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("telegram", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=250)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ads.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
