# Generated by Django 3.2 on 2022-01-17 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0004_customer_supplier"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="CustomerModel",
        ),
        migrations.RenameModel(
            old_name="Profile",
            new_name="ProfileModel",
        ),
        migrations.RenameModel(
            old_name="Supplier",
            new_name="SupplierModel",
        ),
    ]
