# Generated by Django 3.2 on 2022-01-17 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_auto_20220117_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='SupplierModel',
            new_name='Supplier',
        ),
    ]
